name: Publish NPM

on:
    push:
        branches:
            - main

jobs:
    publish_to_npm:
        name: Publish to NPM
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Check Version Bump
              id: check
              uses: EndBug/version-check@v1.1.1

            - uses: pnpm/action-setup@v2.0.1
              if: steps.check.outputs.changed == 'true'
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7
                  run_install: false

            - name: Install Deps
              if: steps.check.outputs.changed == 'true'
              run: pnpm i

            - name: Test
              if: steps.check.outputs.changed == 'true'
              run: pnpm t

            - name: Build
              if: steps.check.outputs.changed == 'true'
              run: pnpm build

            - name: Set NPM Token
              if: steps.check.outputs.changed == 'true'
              uses: filipstefansson/set-npm-token-action@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Publish New Version
              if: steps.check.outputs.changed == 'true'
              run: npm publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
